dnes jsem zacal s cvicenim exercism simple-calculator



poznamky
begin
...
rescue someError
...
end

je stejny jako try catch block

| JavaScript / TypeScript | Ruby                           |
| ----------------------- | ------------------------------ |
| `Error`                 | `StandardError`                |
| `TypeError`             | `TypeError` (v Ruby taky!)     |
| `RangeError`            | `RangeError`                   |
| **(vlastní třída)**     | `ArgumentError`, `CustomError` |
